language: go

go:
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - GO111MODULE=on go mod vendor
  
script:
     - go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
